:fly_host = http://secret-santa.fly.dev
:local = http://localhost:5000

# local
GET http://localhost

## create team
POST :local:5000/partecipants
content-type: application/json
{}
# on fly
GET :FLY_HOST

# fetch people from team
GET :local/people?select-team=1